---
# TODO: support new create-config command to generate node certs and config
# TODO: recreate master/node configs if settings that affect the configs
# change (hostname, public_hostname, ip, public_ip, etc)

# TODO: create a failed_when condition
- name: Create node config
  command: >
    /usr/bin/openshift admin create-node-config
      --node-dir={{ openshift_cert_dir}}/node-{{ item.openshift.common.hostname }}
      --node={{ item.openshift.common.hostname }}
      --hostnames={{ [item.openshift.common.hostname, item.openshift.common.public_hostname]|unique|join(",") }}
      --dns-domain={{ openshift.dns.domain }}
      --dns-ip={{ openshift.dns.ip }}
      --master={{ openshift.master.api_url }}
      --signer-key={{ openshift_cert_dir}}/ca/key.key
      --signer-cert={{ openshift_cert_dir}}/ca/cert.crt
      --certificate-authority={{ openshift_cert_dir }}/ca/cert.crt
      --signer-serial={{ openshift_cert_dir }}/ca/serial.txt
      --listen=https://0.0.0.0:10250
  args:
    chdir: "{{ openshift_cert_dir_parent }}"
    creates: "{{ openshift_cert_dir_abs }}/node-{{ item.openshift.common.hostname }}"
  with_items: openshift_nodes

- name: Register unregistered nodes
  kubernetes_register_node:
    client_user: openshift-client
    name: "{{ item.openshift.common.hostname }}"
    api_version: "{{ openshift_kube_api_version }}"
    cpu: "{{ item.openshift.node.resources_cpu | default(None) }}"
    memory: "{{ item.openshift.node.resources_memory | default(None) }}"
    pod_cidr: "{{ item.openshift.node.pod_cidr | default(None) }}"
    host_ip: "{{ item.openshift.common.ip }}"
    labels: "{{ item.openshift.node.labels | default({}) }}"
    annotations: "{{ item.openshift.node.annotations | default({}) }}"
    external_id: "{{ item.openshift.node.external_id }}"
    # TODO: support customizing other attributes such as: client_config,
    # client_cluster, client_context, client_user
  with_items: openshift_nodes
  register: register_result
