---
- name: Gather facts for node hosts
  hosts: nodes

- name: Configure master instances
  hosts: masters
  vars:
    openshift_sdn_master_url: https://{{ openshift.common.hostname }}:4001
  roles:
  - openshift_master
  - openshift_sdn_master

